/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
<<<<<<< HEAD
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
=======

import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as PricingRouteImport } from './routes/pricing'

import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AccessControlRouteImport } from './routes/access-control'
import { Route as IndexRouteImport } from './routes/index'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
=======

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
=======
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
=======
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessControlRoute = AccessControlRouteImport.update({
  id: '/access-control',
  path: '/access-control',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-control': typeof AccessControlRoute
  '/billing': typeof BillingRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
<<<<<<< HEAD
=======

  '/pricing': typeof PricingRoute
  '/subscription': typeof SubscriptionRoute

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
<<<<<<< HEAD
  '/subscription': typeof SubscriptionRoute
=======

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-control': typeof AccessControlRoute
  '/billing': typeof BillingRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
<<<<<<< HEAD
=======

  '/pricing': typeof PricingRoute
  '/subscription': typeof SubscriptionRoute

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
<<<<<<< HEAD
  '/subscription': typeof SubscriptionRoute
=======

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-control': typeof AccessControlRoute
  '/billing': typeof BillingRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
<<<<<<< HEAD
=======

  '/pricing': typeof PricingRoute
  '/subscription': typeof SubscriptionRoute

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
<<<<<<< HEAD
  '/subscription': typeof SubscriptionRoute
=======

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
<<<<<<< HEAD
=======

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
    | '/access-control'
    | '/billing'
    | '/checkout'
    | '/dashboard'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/subscription'
<<<<<<< HEAD
=======

    | '/dashboard'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/register'
    | '/reset-password'

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
<<<<<<< HEAD
=======

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
    | '/access-control'
    | '/billing'  
    | '/checkout'
    | '/dashboard'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/subscription'
<<<<<<< HEAD
=======

    | '/dashboard'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/register'
    | '/reset-password'

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
    | '/workspace'
  id:
    | '__root__'
    | '/'
<<<<<<< HEAD
=======

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
    | '/access-control'
    | '/billing'
    | '/checkout'
    | '/dashboard'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/subscription'
<<<<<<< HEAD
=======

    | '/dashboard'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/register'
    | '/reset-password'

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessControlRoute: typeof AccessControlRoute
  BillingRoute: typeof BillingRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LibraryRoute: typeof LibraryRoute
<<<<<<< HEAD
=======

  PricingRoute: typeof PricingRoute
  SubscriptionRoute: typeof SubscriptionRoute

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
<<<<<<< HEAD
  SubscriptionRoute: typeof SubscriptionRoute
=======

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
=======

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
=======
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
<<<<<<< HEAD
=======

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-control': {
      id: '/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof AccessControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessControlRoute: AccessControlRoute,
  BillingRoute: BillingRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LibraryRoute: LibraryRoute,
<<<<<<< HEAD
=======

  PricingRoute: PricingRoute,
  SubscriptionRoute: SubscriptionRoute,

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
<<<<<<< HEAD
  SubscriptionRoute: SubscriptionRoute,
=======

>>>>>>> 731470ec75e1ed0aa897f896b78b5eef0ec8ff20
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
